# Generated by Django 4.2 on 2024-08-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='Hoteldin adresi:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='baxasi',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Hoteldin 1 kunlik cenasis:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=255, verbose_name='Hoteldin ati:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Hoteldin suwreti 1:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Hoteldin suwreti 2:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Hoteldin suwreti 3:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='klas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelcategory', verbose_name='Hoteldin kategoriyalari:'),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='klas',
            field=models.CharField(max_length=255, verbose_name='Hoteldin kategoriyalari:'),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Hoteldin slugi:'),
        ),
    ]
